### ISSUE TITLE
添加搜索关键字高亮功能

### ISSUE THREAD

**Issue by pengrui2015** [myst729/vue-json-tree#2]
Leo Deng：
你好。
我把组件输出文字的地方都改成了v-html了，因为我使用搜索关键字高亮就是把输入的文字匹配替换成带html标签的数据，这样tree输出文字就是以html标签输出了，我在标签上加的class就可以加载相应的文字高亮样式了。

现在还有两个问题：
一、在搜索框输入数字时，tree会输出"[Vue JSON Tree] Invalid raw JSON."。
不知道是什么原因，我在用vue-json-pretty也会有这个问题，目前我判断输入的如果是数字就不高亮了。
二、如何自动展开高亮行的父级
你的API只提供了3个参数，不知道有没有办法检测到高亮文字所在行，并展开其父级。

还望指点一二，谢谢！

**Comment by pengrui2015** [comment]
> Leo Deng：
> 你好。
> 我把组件输出文字的地方都改成了v-html了，因为我使用搜索关键字高亮就是把输入的文字匹配替换成带html标签的数据，这样tree输出文字就是以html标签输出了，我在标签上加的class就可以加载相应的文字高亮样式了。
> 
> 现在还有两个问题：
> 一、在搜索框输入数字时，tree会输出"[Vue JSON Tree] Invalid raw JSON."。
> 不知道是什么原因，我在用vue-json-pretty也会有这个问题，目前我判断输入的如果是数字就不高亮了。
> 二、如何自动展开高亮行的父级
> 你的API只提供了3个参数，不知道有没有办法检测到高亮文字所在行，并展开其父级。
> 
> 还望指点一二，谢谢！

问题一：已知number类型数据在插入<span class=\'keyword-bg\'>标签时会报错，只要想办法把number类型转换成string类型即可；
问题二：在if (this.kv) 时，判断this.kv.value里是否存在查询的关键字，是就this.expanded = true，反之this.expanded = false即可。

**Comment by myst729** [comment]
Haven’t been around for a long time. Good to know that you figured out the answers.
