### ISSUE TITLE
please can you provider a way to sort rendering order

### ISSUE THREAD

**Issue by jan4984** [myst729/vue-json-tree#8]
I know threre is no order to keys in a js object, but when rendering them, which key present at first sometimes is very important

**Comment by myst729** [comment]
Following ECMA-262 spec, the order is determined by the literal input, and vice versa.

```js
JSON.parse('{"a":"aa","b":"bb"}') // {a: 'aa', b: 'bb'}
JSON.parse('{"b":"bb","a":"aa"}') // {b: 'bb', a: 'aa'}

JSON.stringify({a: `aa`, b: 'bb'}) // '{"a":"aa","b":"bb"}'
JSON.stringify({b: `bb`, a: 'aa'}) // '{"b":"bb","a":"aa"}'
```

If you have any ideas, we could debate whether it's beyond the boundary of this component or not, then take further action maybe.

**Comment by jan4984** [comment]
ok. make sense.
